### ISSUE TITLE
Specified role id does not exists

### ISSUE THREAD

**Issue by mybigman** [kodeine/laravel-acl#1]
Hi,

Decide to give you package a run as it seems to fit the bill :)

```
/*$role = new \App\Modules\Base\Models\Role();
		
$roleAdmin = $role->create([
	'name' => 'Administrator',
	'slug' => 'administrator',
	'description'=>'manage administration privileges'
]);*/

$user = \App\User::find(1);

// assign role by just a slug
$user->assignRole('administrator');

dd($user);
```

The assignRole fails with...

```
InvalidArgumentException in HasRole.php line 158: Specified role id does not exists.
```

Any ideas @kodeine ?

Thanks.

**Comment by mybigman** [comment]
Too add...

Having a quick debug...

```
// HasRole.php line 156
&& is_null($this->roles()->find($role))
```
This returns null since there is nothing in the role_user table.

**Comment by kodeine** [comment]
@mybigman, i tried your code at my system and it works like a charm. The InvalidArgumentException you're getting is because administrator role was not found in sql. So maybe check if role was created successfully and shows in db. let me know how it goes.

**Comment by Webcris** [comment]
Hi,

I have the same problem... but I find the issue
On HasRole.php:
On first "if" the $find->getKey(); return the key value 1, but you then init $role = $find->getKey() and it's not ok for the rest of "ifs". You must use $role_key or something like this to return.

 
if ( is_string($role) ) {
            $model = new \Kodeine\Acl\Models\Eloquent\Role;
            $find = $model->whereSlug($role)->first();

            if ( ! is_object($find) ) {
                throw new \InvalidArgumentException('Specified role slug does not exists.');
            }

            $role = $find->getKey();
        }

**Comment by kodeine** [comment]
@mybigman @Webcris
i think i know where the problem is, ill commit a fix in few hours.

**Comment by kodeine** [comment]
@mybigman @Webcris Please run composer update and test again, i've pushed some updates. Let me know if this works.

**Comment by mybigman** [comment]
testing if it reopens...

**Comment by mybigman** [comment]
@kodeine 

Can you please reopen this as its fixed but not fixed as a new problem is introduced :)

HasRole.php line 139
```
$key = ctype_alpha($role) ? 'slug' : 'id';
```
You are limiting to alpha only which causes another problem...

I have many modules so i define my slugs like so...

```
$user->assignRole('sam.admin');
$user->assignRole('sam.user');

$user->assignRole('modulex.admin');
$user->assignRole('modulex.user');
...
```

Since it has a dot character is fails.

how about something like...

```
$key = is_numeric($role) ? 'id' : 'slug';
```

that should solve the problem.

Thanks

**Comment by kodeine** [comment]
@mybigman on it now.

**Comment by kodeine** [comment]
@mybigman try it now :) just pushed a fix.

**Comment by mybigman** [comment]
perfect... thanks mate :)
